name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: sudo docker build -t "${DOCKERHUB_USERNAME}"/portfolio:latest .
      - name: Login to DockerHub
        run: sudo docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
      - name: Push Docker Image to DockerHub
        run: sudo docker push "${DOCKERHUB_USERNAME}"/portfolio:latest
